# Netlify Configuration File
# New In Abu Dhabi - Static Site Deployment

[build]
  # Build command - not needed for static HTML sites
  command = "echo 'Static site - no build required'"
  
  # Publish directory - where the site files are located
  publish = "."

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(self)"
    
    # Performance headers
    X-DNS-Prefetch-Control = "on"

# Cache static assets for better performance
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# HTML files cache for shorter time
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Redirects for better SEO and user experience
[[redirects]]
  from = "/home"
  to = "/"
  status = 301

[[redirects]]
  from = "/index"
  to = "/"
  status = 301

# 404 handling - redirect to home page for now
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404